### ISSUE TITLE
针对web开发的疑惑

### ISSUE THREAD

**Issue by 957651480** [go-eagle/eagle#18]
请问前端目录放哪里好了，如果用nginx放静态资源使用哪个目录呢

**Comment by qloog** [comment]
关于web的模板目录是放在 `internal/templates`。

静态文件可以在根目录建立 `static` 目录，里面建立 `js`， `css`， `images` 等目录。

这些都可以在 `router/web.go` 路由文件中进行查看，也可以自定义。

**Comment by 957651480** [comment]
谢谢，要是带个自动生成业务代码的功能的就更完美了

**Comment by 957651480** [comment]
作者go项目分层结构清晰，规范，受教了

**Comment by qloog** [comment]
[要是带个自动生成业务代码的功能的就更完美了] 这个主要是指哪一块呢？

**Comment by 957651480** [comment]
命令行支持数据的migration与seeder ,支持命令行生成基本的curd业务代码

**Comment by zplzpl** [comment]
@957651480 其实你应该用gin-vue-admin，但是他得工程实践做得不是很好，我看过了代码，我用得不舒服。
