### ISSUE TITLE
有关单元测试的疑惑

### ISSUE THREAD

**Issue by yangsui9999** [go-eagle/eagle#27]
感谢作者的贡献。希望能看到更多go 测试相关的 demo。我目前有两个疑惑

1. 相关的测试代码的目录组织结构是怎么样的，比如我的test目录放在那儿。
2. 在目录结构已经确定的情况下，希望能给出更多的demo

谢谢。

**Comment by qloog** [comment]
1、测试代码基本是和功能或者库代码放到一起
2、根目录下的 `test` 目录主要是存放一些和单元测试相关的配置文件，比如启动docker用到的环境配置文件、数据库测试文件等。

感谢关注，后续会补充更多关于单元测试的代码。
