### ISSUE TITLE
请问一下 service 层如何测试

### ISSUE THREAD

**Issue by zoulux** [go-eagle/eagle#29]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

这边我看到 dao 层的测试，想知道 svc 怎么测试，有没有示例

**Comment by qloog** [comment]
两个办法：
1、把 service 依赖的，比如 dao, 通过使用 mock 给 mock 掉
2、使用 docker-compose 启动依赖的服务，然后对 service 进行测试。
第二个测试起来更真实。

**Comment by zoulux** [comment]
方案一 可以提供一些示例进行参考吗，因为还涉及到一些对象的注入
方案二，是不是代价太大，ci 怎么进行落地

**Comment by qloog** [comment]
dao 层的测试可以参考：`internal/dao/user_follow_dao_test.go`
