### ISSUE TITLE
pkg/net/http error

### ISSUE THREAD

**Issue by mszero** [go-eagle/eagle#35]
**Describe the bug**

这个包不能用，本身有问题。你测试下看看，运行不起来。

--- FAIL: TestHttp (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1339e7d]

1.16

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by qloog** [comment]
可以贴一下使用代码的方式。

自测可以使用，具体可以看下新增的test文件： `client_test.go`， 里面有个unit test
