### ISSUE TITLE
Docker 运行报错，panic: config file not found

### ISSUE THREAD

**Issue by ZoeLeee** [go-eagle/eagle#52]
2021/11/28 14:01:51 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
app yaml
panic: config file not found

goroutine 1 [running]:
main.main()
        /go/src/github.com/go-eagle/eagle/main.go:66 +0x7fa

**Comment by ZoeLeee** [comment]
Linux DESKTOP-Q8VGRRH 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by qloog** [comment]
@ZoeLeee 这个和环境配置也有关系，命令行下 `echo $APP_ENV` 查看下环境，可以贴一下具体运行的命令

**Comment by ZoeLeee** [comment]
@qloog 
 `
# 1. build image: docker build -t eagle:v1 -f Dockerfile .
# 2. start: docker run --rm -it -p 8080:8080 eagle:v1
# 3. test: curl -i http://localhost:8080/health
`
运行命令是项目Dockerfile写的。echo $APP_ENV 这个在终端运行没有东西啊

**Comment by qloog** [comment]
已修复，可以pull 代码重新运行下  @ZoeLeee

**Comment by ZoeLeee** [comment]
@qloog  pull后重新跑， docker mysql 连接不上

![image](https://user-images.githubusercontent.com/33168975/143829463-874b5689-177e-4f44-aad1-817dce91086d.png)

**Comment by ZoeLeee** [comment]
![image](https://user-images.githubusercontent.com/33168975/143830236-785f255f-674b-4ae3-bc51-42746594eb52.png)

![image](https://user-images.githubusercontent.com/33168975/143830267-ea777e59-98eb-428a-bca1-b014b657dc15.png)
配置文件这里要改下。不然docker编译不过去

**Comment by qloog** [comment]
> @qloog pull后重新跑， docker mysql 连接不上
> 
> ![image](https://user-images.githubusercontent.com/33168975/143829463-874b5689-177e-4f44-aad1-817dce91086d.png)

这个需要换成自己的本地或者某个远程mysql地址

**Comment by ZoeLeee** [comment]
@qloog  那有点不明白 mysql 容器的作用是什么哦。 可能我主要做前端，Docker还没弄明白

**Comment by qloog** [comment]
@ZoeLeee 如果想在容器里使用127.0.0.1，必须容器内有安装数据库。否则只能连接外部数据库。
可以使用 docker-compose 来启动服务会更简单一些。
