### ISSUE TITLE
密码加解密不对

### ISSUE THREAD

**Issue by ZoeLeee** [go-eagle/eagle#54]

**Comment by ZoeLeee** [comment]
![image](https://user-images.githubusercontent.com/33168975/144003072-70ff0273-6b1d-4ec1-8713-f613a6edaa99.png)
![image](https://user-images.githubusercontent.com/33168975/144003160-00d278f4-92c6-400f-b3fa-b85ded1c6744.png)
@qloog  你密码加密了2次啊

**Comment by qloog** [comment]
可以移除 service里的，DoRegister里的删除
