### ISSUE TITLE
项目的用户密码加密功能被取消了吗

### ISSUE THREAD

**Issue by ZoeLeee** [go-eagle/eagle#57]
![image](https://user-images.githubusercontent.com/33168975/145712125-d6096981-1bbf-40e2-aed8-2ae9220b5145.png)

**Comment by qloog** [comment]
目前不会被取消，都会应用`service.Register` 中的 `auth.HashAndSalt` 被加密。如果需要取消，把 `auth.HashAndSalt` 删除就可以了。

**Comment by ZoeLeee** [comment]
不起作用了，我运行项目调用接口，看数据库没加密，登录的适合又用加密的方式验证
