### ISSUE TITLE
脚手架的日志怎么都在根目录啊

### ISSUE THREAD

**Issue by ZoeLeee** [go-eagle/eagle#58]
![image](https://user-images.githubusercontent.com/33168975/146666883-e9583e1f-5092-4a3b-9372-fe48b00d58d9.png)
在哪里配置啊。config.local,yaml 这个配置没用

**Comment by ZoeLeee** [comment]
![image](https://user-images.githubusercontent.com/33168975/146667328-fd64ecf3-1e9f-464b-8729-1c98db02aab2.png)
这配置文件的数据好像没起作用啊。。。。
还是说脚手架好久没更新了？？？

**Comment by qloog** [comment]
之前是有点没同步，可以更新下最新版试下。
