### ISSUE TITLE
为什么cron作为main包加载, 而不是作为init启动时直接加载呢? 这么设计有什么目的吗?

### ISSUE THREAD

**Issue by hapihacking** [go-eagle/eagle#60]
看到无论是shell脚本还是docker部署时, 实际上cron以及consumer都没有启动;

另外, 使用`eagle new xxx`安装脚手架后, config文件夹下应该像这个repo里分为docker和local的配置文件, 而不是把local配置文件直接放到config文件夹下;

**Comment by qloog** [comment]
1、cron和consumer暂时还没有加入进来，分开的原因是实际线上部署的时候会将这几个分开部署，也就是当做3个独立的应用来部署，互不影响。
2、两个不一样是因为还没有完全同步，不过这也可以看到两种模式的配置方式，详细可以看下文档：[https://go-eagle.org/docs/component/config](https://go-eagle.org/docs/component/config)
@luckyhacking
