### ISSUE TITLE
请问 log 不支持 Debug 级别是出于什么考虑呢？

### ISSUE THREAD

**Issue by luoxiaohei** [go-eagle/eagle#63]
你好，我看之前的代码提交记录，在最初 log.Logger 是支持 Debug 级别的日志记录的，后来在 [chore: optimize log](https://github.com/go-eagle/eagle/commit/96a3b88ed6ee58a9a3d8a34b84e737b7a995bb95) 这次提交中去掉了 Debug 级别的支持。

我理解 Debug 级别的日志和 Info 级别的日志差别还是比较大的。在实践经验中，通常是开发和测试环境中开启 Debug 级别的日志，生产环境中开启 Info 日志，缺少 Debug 级别的日志会对测试环境排查问题有比较大的影响。

想了解下咱们是出于什么原因选择了这样的设计，以及后续是否有计划重新增加对 Debug 级别日志的支持呢？

**Comment by qloog** [comment]
嗯，一开始是支持debug，后来考虑，debug不是很常用，基本的warn,error,info 基本满足需求。 如有需要，也可以考虑加回来。@luoxiaohei

**Comment by luoxiaohei** [comment]
好的，辛苦看下 https://github.com/go-eagle/eagle/pull/62 这个 PR，如果没问题的话先合入下，然后我再提一下关于日志记录器的 PR。

**Comment by qloog** [comment]
Done @luoxiaohei

**Comment by luoxiaohei** [comment]
Debug 级别日志的支持已提交到 https://github.com/go-eagle/eagle/pull/64

**Comment by qloog** [comment]
@luoxiaohei Done
