### ISSUE TITLE
make build 时候出现错误

### ISSUE THREAD

**Issue by cayden** [go-eagle/eagle#66]
当执行make build时候出现错误 

`internal/routers/router.go:13:2: no required module provides package github.com/go-eagle/eagle/docs; to add it:`

**Comment by qloog** [comment]
更新到最新版试下，我本地是OK的。

**Comment by xiaods** [comment]
```
eagle on  master via 🐳 default via 🐹 v1.17.6 on ☁️  xiaods@gmail.com took 32s 
❯ git rebase FETCH_HEAD
Current branch master is up to date.

eagle on  master via 🐳 default via 🐹 v1.17.6 on ☁️  xiaods@gmail.com took 8s 
❯ make build
internal/service/user_service.go:14:2: no required module provides package github.com/go-eagle/eagle/api/user/v1; to add it:
        go get github.com/go-eagle/eagle/api/user/v1
internal/routers/router.go:13:2: no required module provides package github.com/go-eagle/eagle/docs; to add it:
        go get github.com/go-eagle/eagle/docs
make: *** [build] Error 1
```

**Comment by wonderfate** [comment]
> ```
> eagle on  master via 🐳 default via 🐹 v1.17.6 on ☁️  xiaods@gmail.com took 32s 
> ❯ git rebase FETCH_HEAD
> Current branch master is up to date.
> 
> eagle on  master via 🐳 default via 🐹 v1.17.6 on ☁️  xiaods@gmail.com took 8s 
> ❯ make build
> internal/service/user_service.go:14:2: no required module provides package github.com/go-eagle/eagle/api/user/v1; to add it:
>         go get github.com/go-eagle/eagle/api/user/v1
> internal/routers/router.go:13:2: no required module provides package github.com/go-eagle/eagle/docs; to add it:
>         go get github.com/go-eagle/eagle/docs
> make: *** [build] Error 1
> ```

我也是这个飘红了

**Comment by qloog** [comment]
@wonderfate 执行如下命令

go get github.com/go-eagle/eagle/api/user/v1
go get github.com/go-eagle/eagle/docs

**Comment by BDon-Tan** [comment]
`github.com/go-eagle/eagle/internal/routers imports
	github.com/go-eagle/eagle/docs: no matching versions for query "latest"
github.com/go-eagle/eagle/internal/service imports
	github.com/go-eagle/eagle/api/user/v1: no matching versions for query "latest"
 ✘ Don@Dons-MacBook-Pro  ~/GolandProjects/eagle   master  go mod tidy
go: finding module for package github.com/go-eagle/eagle/docs
go: finding module for package github.com/go-eagle/eagle/api/user/v1
github.com/go-eagle/eagle/internal/routers imports
	github.com/go-eagle/eagle/docs: no matching versions for query "latest"
github.com/go-eagle/eagle/internal/service imports
	github.com/go-eagle/eagle/api/user/v1: no matching versions for query "latest"
 ✘ Don@Dons-MacBook-Pro  ~/GolandProjects/eagle   master  go get github.com/go-eagle/eagle/api/user/v1

go: github.com/go-eagle/eagle/api/user/v1: no matching versions for query "upgrade"
 ✘ Don@Dons-MacBook-Pro  ~/GolandProjects/eagle   master  go get github.com/go-eagle/eagle/docs
go: github.com/go-eagle/eagle/docs: no matching versions for query "upgrade"
 ✘ Don@Dons-MacBook-Pro  ~/GolandProjects/eagle   master `

**Comment by BDon-Tan** [comment]
> `github.com/go-eagle/eagle/internal/routers imports github.com/go-eagle/eagle/docs: no matching versions for query "latest" github.com/go-eagle/eagle/internal/service imports github.com/go-eagle/eagle/api/user/v1: no matching versions for query "latest" ✘ Don@Dons-MacBook-Pro  ~/GolandProjects/eagle   master  go mod tidy go: finding module for package github.com/go-eagle/eagle/docs go: finding module for package github.com/go-eagle/eagle/api/user/v1 github.com/go-eagle/eagle/internal/routers imports github.com/go-eagle/eagle/docs: no matching versions for query "latest" github.com/go-eagle/eagle/internal/service imports github.com/go-eagle/eagle/api/user/v1: no matching versions for query "latest" ✘ Don@Dons-MacBook-Pro  ~/GolandProjects/eagle   master  go get github.com/go-eagle/eagle/api/user/v1
> 
> go: github.com/go-eagle/eagle/api/user/v1: no matching versions for query "upgrade" ✘ Don@Dons-MacBook-Pro  ~/GolandProjects/eagle   master  go get github.com/go-eagle/eagle/docs go: github.com/go-eagle/eagle/docs: no matching versions for query "upgrade" ✘ Don@Dons-MacBook-Pro  ~/GolandProjects/eagle   master `

应该是放置的一些资源下载不到了

**Comment by wonderfate** [comment]
> @wonderfate 执行如下命令
> 
> go get github.com/go-eagle/eagle/api/user/v1 go get github.com/go-eagle/eagle/docs

这两个包拉不到

**Comment by qloog** [comment]
已修复，可以重新拉取下再试试。 @xiaods @wonderfate @BDon-Tan @cayden
