### ISSUE TITLE
【BUG反馈&求助&急急】 code, msg 返回异常。grpc请求符合预期，http请求不符合预期。

### ISSUE THREAD

**Issue by SonderEASE** [go-eagle/eagle#85]
**Describe the bug**
grpc服务无法修改code, msg等信息

#我的错误定义
`ValidFailedError = errcode.New(401, "验证失败")`
接口实现：
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/37165936/225612795-0359919d-6ffd-417c-a5fa-a2733d9bd64a.png">

在触发错误的时候，返回的错误是:
<img width="183" alt="image" src="https://user-images.githubusercontent.com/37165936/225612631-dfb56745-de2d-485b-bcee-3044c3db31b9.png">

协议部分
<img width="619" alt="image" src="https://user-images.githubusercontent.com/37165936/225613226-7227e0f9-ea55-41b6-8cf3-5af99634efb7.png">

也就是return的err并没有生效， 求大佬帮忙解决！！跪求，十万火急啊

通过debug发现
<img width="378" alt="image" src="https://user-images.githubusercontent.com/37165936/225613847-dc75b2c9-0f26-4de7-8390-407173925690.png">

在自定生成的xxx_gin.pb.go文件中，代码没有进到这个if里
<img width="378" alt="image" src="https://user-images.githubusercontent.com/37165936/225614049-d8631303-f77d-4a60-810f-2f4cbcfceccb.png">
我的服务既想提供grpc接口，又想提供http请求接口，所以用了grpc-gateway 并使用了以下编译指令。
<img width="678" alt="image" src="https://user-images.githubusercontent.com/37165936/225789041-dd701195-c6b9-4cf8-8564-94d438e1e103.png">

目前就是http接口返回的code,msg不符合预期，求大佬指点

**Comment by SonderEASE** [comment]
@appleboy @qloog @flw-cn @luoxiaohei 大哥们有空能帮忙看看么

**Comment by appleboy** [comment]
why tag me?

**Comment by SonderEASE** [comment]
> why tag me?

sorry for that.   @  prompts a list of names,  I thought it was a related member

**Comment by SonderEASE** [comment]
@qloog  我找到问题了，生成的_gin.pb文件中处理错误的方法中定义的接口iCode 需要实现以下三个接口：
`HTTPCode() int`
`Message() string`
`Code() int`
但是eagle的错误类型没有实现Message()&HTTPCode() 这两个方法，只有Msg() & Code()
可以给我个权限我来修复下这个问题

**Comment by SonderEASE** [comment]
> @SonderEASE 错误分两种， 一种是属于系统类的错误，比如404、参数错误、内部错误， 另一种是 业务内错误，这时可以返回具体的业务错误码，比如用户已存在：`errcode.New(20100, "The user already exists.")`
> 
> 全部内容如下：
> 
> ```
> var (
> 	// common errors
> 	ErrSuccess         = errcode.New(codes.OK, "Ok")
> 	ErrInvalidArgument = errcode.New(codes.InvalidArgument, "Invalid argument")
> 	ErrInternalError   = errcode.New(codes.Internal, "Internal error")
> 	ErrAccessDenied    = errcode.New(codes.PermissionDenied, "Access denied")
> 	ErrNotFound        = errcode.New(codes.NotFound, "Not found")
> 
> 	// biz errors
> 	ErrUserIsExist = errcode.New(20100, "The user already exists.")
> )
> ```
> 
> 如果有改进建议可以提交PR。

这个我能理解， 问题是说这个错误类型，没有实现
`HTTPCode() int`
`Message() string`
这两个接口，而通过make生成的xxx_gin.pb.go文件中，解析错误的接口是
```
type iCode interface {
	HTTPCode() int
	Message() string
	Code() int
}
```
因为没实现所以，errors.As(err, &c) 这个解析会失败。

**Comment by qloog** [comment]
这个interface `iCode ` 是在哪里看到的？新版本应该是没有这个了。 @SonderEASE

**Comment by SonderEASE** [comment]
> 这个interface `iCode ` 是在哪里看到的？新版本应该是没有这个了。 @SonderEASE

```
protoc --proto_path=. \
           --proto_path=./third_party \
           --go_out=. --go_opt=paths=source_relative \
           --go-grpc_out=. --go-grpc_opt=paths=source_relative \
           $(API_PROTO_FILES)
```

这个make语句生成的，_gin.pb.go文件中都有iCode  是我本地protoc需要升级么？ @qloog

**Comment by qloog** [comment]
升级下eagle:  `eagle upgrade`, 里面会升级生成 `gin.pb.go`代码的命令。  @SonderEASE

**Comment by SonderEASE** [comment]
> eagle upgrade

牛逼！ 我再请教一个问题，我现在要适配旧的接口，旧的接口返回的数据是这个格式的：
`{
    "code": 0,
    "data": [],
    "msg": "成功"
}`
这个data是个数组，我能让根据protoc生成的 http响应body中的data也是数组么？ 或者有啥选项能把自带的这三个字段去掉
@qloog

**Comment by qloog** [comment]
目前还不支持自定义整体的返回格式，比如
```
{
    "code":0,
    "data":[],
    "msg":"成功"
}
```
改为
```
{
    "errcode":0,
    "data":[],
    "message":"成功"
}
```
不过从扩展性上考虑的话，data使用map(`{}`)可能会更好一些。

@SonderEASE

**Comment by SonderEASE** [comment]
> 目前还不支持自定义整体的返回格式，比如
> 
> ```
> {
>     "code":0,
>     "data":[],
>     "msg":"成功"
> }
> ```
> 
> 改为
> 
> ```
> {
>     "errcode":0,
>     "data":[],
>     "message":"成功"
> }
> ```
> 
> 不过从扩展性上考虑的话，data使用map(`{}`)可能会更好一些。
> 
> @SonderEASE

感谢！

**Comment by qloog** [comment]
有两种办法可以实现：
第一种：使用脚本替换现有gin.pb里的 `app.Success` 同时替换import的包
第二种：参考现有的插件实现一个自己的扩展，参考：https://github.com/go-eagle/eagle/tree/master/cmd/protoc-gen-go-gin，然后修改makefile，改为自己的插件即可。

以上供参考。

@SonderEASE
