### ISSUE TITLE
我该如何给基于grpc的http请求返回设置headers?

### ISSUE THREAD

**Issue by SonderEASE** [go-eagle/eagle#87]
一个登录接口，在响应中我需要设置一个header, token用来给用户后续验证登录信息。
我尝试使用了gin的中间件，在router文件中加入了
`g.Use(setHttpResponseWriter())`
```
func setHttpResponseWriter() gin.HandlerFunc {
	return func(c *gin.Context) {
		ctx := c.Request.Context()

		// 将 HTTP 请求和响应存储到 gRPC 上下文中
		ctx = context.WithValue(ctx, "writer", c.Writer)

		c.Request = c.Request.WithContext(ctx)
		c.Next()
	}
}
```
`c, ok := ctx.Value("writer").(gin.ResponseWriter)`
但是这种方式无法获取到我设置在ctx中的gin.ResponseWriter 请教该如何处理呢？

**Comment by qloog** [comment]
@SonderEASE 关的挺快的嘛，最后是如何处理的？

**Comment by SonderEASE** [comment]
> @SonderEASE 关的挺快的嘛，最后是如何处理的？

我看了下代码这块
```
        md := metadata.New(nil)
	for k, v := range ctx.Request.Header {
		md.Set(k, v...)
	}
	newCtx := metadata.NewIncomingContext(ctx, md)
```
这块应该是只支持这种request header 字符串的这种传递方式，所以想要获取gin的writer目前应该不支持， 所以我就让前端支持设置Set-cookie了 我给前端照常返回token字段就可以了
